framework:
    asset_mapper:
        paths:
            - assets/
        missing_import_mode: strict
        excluded_patterns:
            - '*/assets/styles/_*.scss'
            - '*/assets/styles/**/_*.scss'
    assets:
        json_manifest_path: "%kernel.project_dir%/public/assets/manifest.json"

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn

sensiolabs_typescript:
    source_dir: ['%kernel.project_dir%/assets']
