version: '3.3'

services:
  phptest:
    extends:
      file: docker-compose.codestyle.yml
      service: phpcodestyle
    links:
      - dbtest
    networks:
      - test
    environment:
      DATABASE_URL: postgresql://test:test@dbtest:5432/test?serverVersion=15&charset=utf8
  dbtest:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    networks:
      - test

networks:
  test:
