version: '3.3'

services:
  phpcodestyle:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/srv/app:delegated
    working_dir: /srv/app  

networks:
  codestyle:
