version: '3.3'

services:
  nginx:
    build:
      context: ./docker/nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/srv/app:delegated
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - dev
  php:
    user: '${USER_ID}:${GROUP_ID}'
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/srv/app:delegated
      - ./docker/php/conf.d/php.ini:/usr/local/etc/php/conf.d/app.ini
    working_dir: /srv/app
    depends_on:
      - db
    environment:
      APP_ENV: dev
    networks:
      - dev
  db:
    restart: unless-stopped
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: recettes
      POSTGRES_USER: recettes
      POSTGRES_DB: recettes
      TZ: Europe/Paris
      PGTZ: Europe/Paris
    volumes:
      - ./docker/db:/var/lib/postgresql/data
      - ./var:/srv/app/var
    networks:
      - dev
  node:
    user: '${USER_ID}:${GROUP_ID}'
    build:
      context: ./docker/node
    command: pnpm run dev-server
    working_dir: /srv/app
    volumes:
      - .:/srv/app
    ports:
      - "3000:3000"

volumes:
  db-data:
    driver: local

networks:
  dev:
