version: '3'

silent: true

env:
    USER_ID: 0
    GROUP_ID: 0
    compose_codestyle: "USER_ID=0 GROUP_ID=0 docker compose -f ../../docker-compose.codestyle.yml"

tasks:
    install:
        desc: Install phpstan
        cmds:
            - "{{.compose_codestyle}} run --rm phpcodestyle composer require --dev --working-dir=tools/phpstan phpstan/phpstan"
            - "{{.compose_codestyle}} run --rm phpcodestyle composer require --dev --working-dir=tools/phpstan phpstan/phpstan-phpunit"
            - "{{.compose_codestyle}} run --rm phpcodestyle composer require --dev --working-dir=tools/phpstan phpstan/phpstan-symfony"
            - "{{.compose_codestyle}} run --rm phpcodestyle composer require --dev --working-dir=tools/phpstan phpstan/phpstan-doctrine"
        status:
            - test -f ./vendor/bin/phpstan
            - test -f ./vendor/phpstan/phpstan-phpunit/extension.neon
            - test -f ./vendor/phpstan/phpstan-symfony/extension.neon
            - test -f ./vendor/phpstan/phpstan-symfony/rules.neon
            - test -f ./vendor/phpstan/phpstan-doctrine/extension.neon
    exec:
        desc: Execute phpstan
        cmds:
            - task: install
            - "{{.compose_codestyle}} run --rm phpcodestyle tools/phpstan/vendor/bin/phpstan --memory-limit=-1 analyze -c tools/phpstan/phpstan.neon"
