version: '3'

silent: true

env:
    USER_ID: 0
    GROUP_ID: 0
    compose_codestyle: "USER_ID=0 GROUP_ID=0 docker compose -f ../../docker-compose.codestyle.yml"

tasks:
    install:
        desc: Install phpcs
        cmds:
            - "{{.compose_codestyle}} run --rm phpcodestyle composer require --dev --working-dir=tools/phpcs squizlabs/php_codesniffer"
        status:
            - test -f ./vendor/bin/phpcbf
    exec:
        desc: Execute phpcs
        cmds:
            - task: install
            - "{{.compose_codestyle}} run --rm phpcodestyle tools/phpcs/vendor/bin/phpcbf src"
