services:
    frontend:
        build:
            context: services/php
            target: frontend
        depends_on:
            - postgres
        volumes:
            - "../..:/var/www:cached"
        environment:
            - "PHP_VERSION=${PHP_VERSION}"
        ports:
            - "8000:8000"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.myproject.rule=Host(`localhost`)"
            - "traefik.http.routers.myproject.entrypoints=http"
            - "traefik.http.services.myproject.loadbalancer.server.port=80"
            - "traefik.http.middlewares.forwardedheaders.headers.customRequestHeaders.X-Forwarded-Proto=http"
        networks:
            - app_network

    postgres:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: recettes
            POSTGRES_PASSWORD: recettes
            POSTGRES_DB: recettes
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - app_network

volumes:
    db_data: {}

networks:
    app_network:
        driver: bridge
