services:
    router:
        networks:
            - app_network
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"

networks:
    app_network:
        driver: bridge
